# Configuração do Monitor de Ping para EasyPanel
# Copie este arquivo para .env no EasyPanel

# === CONFIGURAÇÕES BÁSICAS ===
MONITOR_HOST=8.8.8.8
PING_INTERVAL=1
MAX_FAILURES=3

# === EVOLUTION API ===
EVOLUTION_API_KEY=B6D711FCDE4D4FD5936544120E713976
WHATSAPP_API_URL=http://evolution-api:8080
WHATSAPP_INSTANCE=ping-monitor
WHATSAPP_NUMBER=5511999999999

# === TELEGRAM (OPCIONAL) ===
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# === WEBHOOK (OPCIONAL) ===
WEBHOOK_URL=

# === BANCO DE DADOS ===
MONGODB_PASSWORD=evolution123
REDIS_PASSWORD=redis123

# === TIMEZONE ===
TZ=America/Sao_Paulo
